# Generated by Django 5.2.1 on 2025-05-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterField(
            model_name='user',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
