# Generated by Django 5.2.1 on 2025-05-12 18:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('api_url', models.URLField()),
                ('api_key', models.TextField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_parameters', models.JSONField(default=dict)),
            ],
        ),
    ]
