# Generated by Django 5.2.1 on 2025-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='default_parameters',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
