# Generated by Django 5.2.1 on 2025-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0002_alter_model_default_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='default_parameters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
